name: Ratings
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        name: checkout code
    
      - uses: docker/setup-buildx-action@v1    
        name: Docker build
      
      - name: Login to github registry
        uses: docker/login-action@v1 
        with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.TOKEN_GITHUB__BP }}
        
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/pungpeee/bookinfo-rating:latest
          
      - name: Deploy compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: pungpeee
          password: ${{ secrets.PASSWORD }}
          source: "./databases"
          target: "./bookinfo-rating-databases"    
        
  deploy:
      needs: build
      runs-on: ubuntu-latest
      
      steps:
        - name: Execute ssh command to remote server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: pungpeee
            password: ${{ secrets.PASSWORD }}
            script: |
               docker pull ghcr.io/pungpeee/bookinfo-rating:latest
               docker run -d --name mongodb -p 27017:27017 --network=bookinfo -v ~/bookinfo-rating-databases:/docker-entrypoint-initdb.d bitnami/mongodb:4.4.4-debian-10-r5
               docker run -d --name ratings -p 8081:8080 --network=bookinfo --link mongodb:mongodb -e SERVICE_VERSION=v2 -e 'MONGO_DB_URL=mongodb://mongodb:27017/ratings' ghcr.io/pungpeee/bookinfo-rating:latest
